version: '3.7'
services:
    postgres:
        image: postgres:12.3
        container_name: postgres
        environment:
            POSTGRES_DB: vendure
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c pg_stat_statements.max=100000 -c max_connections=200
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.18
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@localhost.dev
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - '8081:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        links:
            - 'postgres:pgsql-server'
    keycloak:
        image: quay.io/keycloak/keycloak
        ports:
            - '9000:8080'
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        command:
            - start-dev
            - --import-realm
        volumes:
            - keycloak_data:/opt/keycloak/data
volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local

    phpmyadmin_data:
        driver: local
    keycloak_data:
        driver: local
